server:
  port: 8080
  servlet:
    context-path: /three
spring:
  datasource:
    druid:
      db1:
        url: jdbc:mysql://172.31.235.64:3306/bme_prod?characterEncoding=utf-8&useSSL=false&autoReconnect=true
        username: bme
        password: Bme@709394
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
